[target.thumbv7em-none-eabihf]
runner = [
    "probe-rs",
    "run",
    "--connect-under-reset",
    "--chip",
    "STM32H747XIHx",
    "--log-format",
    "{t} {L:severity} {s}"
]

rustflags = [
    # "-C", "linker=flip-link",
    #"-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"   # Cortex-M4F (with FPU)

[env]
DEFMT_LOG = "trace"
