[package]
name = "redpitaya"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"
linux-embedded-hal = "0.4.0"
memmap2 = "0.9.5"
postcard = { version = "1.1.1", features = ["use-std"] }
rand = "0.9.1"
rand_distr = "0.5.1"
serde = "1.0.219"
